- name: installing maven to the system
  ansible.builtin.dnf:  
    name: maven
    state:  installed

- name: app setup
  include_role:
    name: common
    tasks_from: app-setup



- name: Install maven dependies
  ansible.builtin.command:  mvn clean package
  args:
    chdir: /app

- name: renaming the file
  ansible.builtin.command:  mv target/shipping-1.0.jar shipping.jar 
  args:
    chdir: /app

- name: installing systemd
  include_role:
    name: common
    tasks_from: systemd.yaml

    

