- name: copy the mongo service
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: just for reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable catalougue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes